#!/bin/bash

today()  
{  
    date +%Y-%m-%d  
}  

echo 'Post title: '
read NAME
number=$((RANDOM%11+1))
echo '---
layout: post
title: '"$NAME"'
modified: '"$(today)"'
description: 
image:
  feature: abstract-'"$number"'.jpg
github: 
tags: [words]
comments: true
share: true
---
' > "_posts/$(today)-${NAME// /-}.md"
emacs "_posts/$(today)-${NAME// /-}.md"